# Generated by Django 2.2.3 on 2019-07-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workname', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
